# yaml-language: $schema=./node_modules/envio/evm.schema.json
name: ai-yield-agent-indexer
description: AI Yield Agent - DeFi Pool Indexer for Monad Testnet

# Global contract definitions
contracts:
  - name: UniswapV2Factory
    handler: src/EventHandlers.ts
    events:
      - event: "PairCreated(address indexed token0, address indexed token1, address pair, uint256)"
  - name: UniswapV2Pair
    handler: src/EventHandlers.ts
    events:
      - event: "Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)"
      - event: "Mint(address indexed sender, uint256 amount0, uint256 amount1)"
      - event: "Burn(address indexed sender, uint256 amount0, uint256 amount1, address indexed to)"
      - event: "Sync(uint112 reserve0, uint112 reserve1)"

# Monad Testnet configuration
networks:
  - id: 10143  # Official Monad Testnet Chain ID
    start_block: 0  # HyperSync will automatically find the first block
    contracts:
      - name: UniswapV2Factory
        address:
          - "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"  # Example factory address
      - name: UniswapV2Pair
        address:
          - "0x742d35Cc6634C0532925a3b8D4C9db4C8b9b8b8b"  # USDC/ETH pair
          - "0x853d955aCEf822Db058eb8505911ED77F175b99e"  # DAI/USDC pair
          - "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"  # UNI/ETH pair

# Enhanced field selection for comprehensive data
field_selection:
  transaction_fields:
    - "hash"
    - "transactionIndex"
    - "from"
    - "to"
    - "value"
    - "gasUsed"
    - "gasPrice"
  block_fields:
    - "number"
    - "timestamp"
    - "hash"
    - "parentHash"

# Performance optimizations
unordered_multichain_mode: false  # Single chain, keep ordered
preload_handlers: true  # Enable preload optimization
raw_events: true  # Store raw events for debugging
rollback_on_reorg: true  # Handle blockchain reorgs