name: ai-yield-agent-monad
description: AI Yield Agent HyperIndex indexer for Monad Testnet

networks:
- id: 10143  # Monad Testnet
  start_block: 0
  contracts:
  - name: USDCToken
    address:
    - 0xf817257fed379853cDe0fa4F97AB987181B1E5Ea  # USDC testnet
    handler: src/EventHandlers.ts
    events:
    - event: Transfer(address indexed from, address indexed to, uint256 value)
    - event: Approval(address indexed owner, address indexed spender, uint256 value)
  - name: UniswapV3Factory
    address:
    - 0x961235a9020b05c44df1026d956d1f4d78014276  # Uniswap V3 Factory
    handler: src/EventHandlers.ts
    events:
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: UniswapV3Pool
    address:
    - 0x742d35Cc6634C0532925a3b8D4C9db4C8b9b8b8b  # Example pool
    handler: src/EventHandlers.ts
    events:
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
    - event: Mint(address sender, address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)
    - event: Burn(address indexed owner, int24 indexed tickLower, int24 indexed tickUpper, uint128 amount, uint256 amount0, uint256 amount1)